In [4]:
import numpy as np
import xarray as xr
from tqdm import tqdm
import scipy.ndimage as snd

In [2]:
path = './'

In [13]:
frt_dat = xr.open_dataset(path+'gradEPT_Frontal_percentile.nc')

# select the largest score from surrounding grid points and times
# We don't need to worry about scores in the edges, spatially because there are no extreme events there.
# we do need to worry about the first and last time step

frt_buffer = snd.maximum_filter(frt_dat['gradEPT_percentile_AboveMedian'],size=(3,3,3),mode='constant',cval=0.)
frt_dat['gradEPT_percentile_AboveMedian_Buffer3x3x3'] = frt_buffer
frt_dat.to_netcdf(path+'gradEPT_Frontal_percentile.nc',mode='a')
frt_dat.close()
del frt_buffer

In [10]:
vrt_dat = xr.open_dataset(path+'PositiveRelativeVorticityAdvection_Percentile.nc')

# select the largest score from surrounding grid points and times
# We don't need to worry about scores in the edges, spatially because there are no extreme events there.
# we do need to worry about the first and last time step

vrt_buffer = snd.maximum_filter(vrt_dat['PositiveRelativeVorticityAdvection_Percentile'],size=(3,3,3),mode='constant',cval=0.)
vrt_dat['PositiveRelativeVorticityAdvection_Percentile_Buffer3x3x3'] = vrt_buffer
vrt_dat.to_netcdf(path+'PositiveRelativeVorticityAdvection_Percentile.nc',mode='a')
vrt_dat.close()
del vrt_buffer



[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
vrt_dat = xr.open_dataset(path+'PositiveTotalVorticityAdvection_Percentile.nc')

# select the largest score from surrounding grid points and times
# We don't need to worry about scores in the edges, spatially because there are no extreme events there.
# we do need to worry about the first and last time step

vrt_buffer = snd.maximum_filter(vrt_dat['PositiveTotalVorticityAdvection_Percentile'],size=(3,3,3),mode='constant',cval=0.)
vrt_dat['PositiveTotalVorticityAdvection_Percentile_Buffer3x3x3'] = vrt_buffer
vrt_dat.to_netcdf(path+'PositiveTotalVorticityAdvection_Percentile.nc',mode='a')
vrt_dat.close()
del vrt_buffer